name: Claude Review

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  claude-review:
    if: |
      (github.event_name == 'issues'                      && contains(github.event.issue.body,   '@claude')) ||
      (github.event_name == 'issue_comment'               && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review'         && contains(github.event.review.body,  '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude'))
    
    runs-on: ubuntu-latest
    
    # 推奨: 最小限の権限のみ付与
    permissions:
      contents:      read  # Repository 内の権限
      pull-requests: read  # PR 内コメントの権限
      issues:        read  # Issueコメントの権限
      actions:       read  # Actionsログへの権限
      id-token:      write # 実行時に適切な権限を取得
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Claude Review
        uses: ./
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
